"""Global CLI installer: make `focux` available on ANY machine.

`focux install` writes portable launchers (``focux``, ``focux.cmd``,
``focux-web``, ``focux-web.cmd``) into a bin directory so the CLI works from
any CWD without pip. With ``--mcp`` it registers the thefocux MCP server at
USER level (Codex ``~/.codex/config.toml``; Claude Code instructions printed
- `claude mcp add` is the supported route there).

The launchers embed the repo path, so they keep working after a machine
restart and work for any Python 3.11+ interpreter. Pure stdlib, zero deps.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path

from .attach import append_codex_toml, mcp_server_config, merge_mcp_json

#: POSIX launcher: a python script with the repo baked in (works on
#: macOS/Linux/Windows-python alike).
_LAUNCHER = '''#!/usr/bin/env python3
"""THE FOCUX CLI launcher (generated by `focux install`). Do not edit."""
import sys
from pathlib import Path

_REPO = r"{repo}"
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from {module} import main

if __name__ == "__main__":
    raise SystemExit(main())
'''

#: Windows launcher: a .cmd that calls the embedded interpreter directly
#: (no reliance on `python` being on PATH at runtime).
_CMD = '''@echo off
"{python}" "%~dp0{name}" %*
'''


@dataclass
class InstallReport:
    created: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    prefix: Path | None = None

    def as_dict(self) -> dict[str, object]:
        return {
            "created": self.created,
            "updated": self.updated,
            "skipped": self.skipped,
            "notes": self.notes,
            "prefix": str(self.prefix) if self.prefix else "",
        }


def default_prefix() -> Path:
    """~/.thefocux/bin on any OS (Windows uses %USERPROFILE%)."""
    home = Path(os.environ.get("USERPROFILE") or Path.home())
    return home / ".thefocux" / "bin"


def install_launchers(
    prefix: Path, repo_root: Path
) -> list[str]:
    """Write the portable launchers; returns the created file paths."""
    prefix = prefix.resolve()
    prefix.mkdir(parents=True, exist_ok=True)
    created: list[str] = []
    repo = str(repo_root.resolve())
    for name, module in (("focux", "focux"), ("focux-web", "webui")):
        launcher = prefix / name
        launcher.write_text(
            _LAUNCHER.format(repo=repo, module=module), encoding="utf-8"
        )
        try:
            launcher.chmod(0o755)
        except OSError:
            pass  # Windows: no chmod semantics
        created.append(str(launcher))
        cmd = prefix / f"{name}.cmd"
        cmd.write_text(_CMD.format(python=sys.executable, name=name),
                       encoding="utf-8")
        created.append(str(cmd))
    return created


def user_home() -> Path:
    """The user's home (works on Windows/macOS/Linux alike)."""
    return Path(os.environ.get("USERPROFILE") or Path.home())


def user_mcp_paths(home: Path | None = None) -> dict[str, Path]:
    """The user-level config file each agent reads for MCP servers."""
    home = home or user_home()
    return {
        "codex": home / ".codex" / "config.toml",
        "claude": home / ".claude.json",
        "cursor": home / ".cursor" / "mcp.json",
    }


def register_user_mcp(
    repo_root: Path,
    *,
    codex_config: Path | None = None,
    claude_config: Path | None = None,
    cursor_config: Path | None = None,
) -> InstallReport:
    """Register thefocux MCP at USER level for ANY coding agent.

    - **Codex**: appends ``[mcp_servers.thefocux]`` to ``~/.codex/config.toml``
      (safe merge - other sections preserved, never duplicated).
    - **Claude Code**: merges the server into ``~/.claude.json`` top-level
      ``mcpServers`` (all other keys preserved).
    - **Cursor**: merges into ``~/.cursor/mcp.json`` (all other servers kept).

    Every merge is idempotent and non-destructive; agents pick the server up
    on their next start. Restart Claude Code / Cursor / Codex to load it.
    """
    report = InstallReport()
    server = mcp_server_config(repo_root)
    paths = user_mcp_paths()

    append_codex_toml(codex_config or paths["codex"], server, report)
    merge_mcp_json(claude_config or paths["claude"], server, report,
                   "claude ~/.claude.json")
    merge_mcp_json(cursor_config or paths["cursor"], server, report,
                   "cursor ~/.cursor/mcp.json")
    report.notes.append(
        "Restart your agents (Claude Code, Cursor, Codex) to load the server."
    )
    return report


def user_mcp_registered(home: Path | None = None) -> dict[str, bool]:
    """Probe which agents have thefocux MCP registered at user level.

    Used by `focux doctor` to verify the install without touching configs.
    """
    home = home or user_home()
    out: dict[str, bool] = {}
    for agent, path in user_mcp_paths(home).items():
        if not path.exists():
            out[agent] = False
            continue
        try:
            text = path.read_text(encoding="utf-8")
            out[agent] = "thefocux" in text
        except OSError:
            out[agent] = False
    return out
