"""Global CLI installer: make `focux` available on ANY machine.

`focux install` writes portable launchers (``focux``, ``focux.cmd``,
``focux-web``, ``focux-web.cmd``) into a bin directory so the CLI works from
any CWD without pip. With ``--mcp`` it registers the thefocux MCP server at
USER level (Codex ``~/.codex/config.toml``; Claude Code instructions printed
- `claude mcp add` is the supported route there).

The launchers embed the repo path, so they keep working after a machine
restart and work for any Python 3.11+ interpreter. Pure stdlib, zero deps.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path

from .attach import append_codex_toml, mcp_server_config

#: POSIX launcher: a python script with the repo baked in (works on
#: macOS/Linux/Windows-python alike).
_LAUNCHER = '''#!/usr/bin/env python3
"""THE FOCUX CLI launcher (generated by `focux install`). Do not edit."""
import sys
from pathlib import Path

_REPO = r"{repo}"
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from {module} import main

if __name__ == "__main__":
    raise SystemExit(main())
'''

#: Windows launcher: a .cmd that calls the embedded interpreter directly
#: (no reliance on `python` being on PATH at runtime).
_CMD = '''@echo off
"{python}" "%~dp0{name}" %*
'''


@dataclass
class InstallReport:
    created: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    prefix: Path | None = None

    def as_dict(self) -> dict[str, object]:
        return {
            "created": self.created,
            "updated": self.updated,
            "skipped": self.skipped,
            "notes": self.notes,
            "prefix": str(self.prefix) if self.prefix else "",
        }


def default_prefix() -> Path:
    """~/.thefocux/bin on any OS (Windows uses %USERPROFILE%)."""
    home = Path(os.environ.get("USERPROFILE") or Path.home())
    return home / ".thefocux" / "bin"


def install_launchers(
    prefix: Path, repo_root: Path
) -> list[str]:
    """Write the portable launchers; returns the created file paths."""
    prefix = prefix.resolve()
    prefix.mkdir(parents=True, exist_ok=True)
    created: list[str] = []
    repo = str(repo_root.resolve())
    for name, module in (("focux", "focux"), ("focux-web", "webui")):
        launcher = prefix / name
        launcher.write_text(
            _LAUNCHER.format(repo=repo, module=module), encoding="utf-8"
        )
        try:
            launcher.chmod(0o755)
        except OSError:
            pass  # Windows: no chmod semantics
        created.append(str(launcher))
        cmd = prefix / f"{name}.cmd"
        cmd.write_text(_CMD.format(python=sys.executable, name=name),
                       encoding="utf-8")
        created.append(str(cmd))
    return created


def register_user_mcp(
    repo_root: Path,
    *,
    codex_config: Path | None = None,
) -> InstallReport:
    """Register thefocux MCP at USER level (Codex; Claude gets instructions).

    Codex: appends ``[mcp_servers.thefocux]`` to ``~/.codex/config.toml``
    (safe merge - other sections preserved, never duplicated).
    """
    report = InstallReport()
    server = mcp_server_config(repo_root)
    cfg = codex_config or (
        Path(os.environ.get("USERPROFILE") or Path.home()) / ".codex" / "config.toml"
    )
    append_codex_toml(cfg, server, report)
    report.notes.append(
        "Claude Code: run `claude mcp add thefocux -- "
        f"{server['command']} {server['args'][0]}` to register the brain"
    )
    return report
